### ISSUE TITLE
Crash when attempting to play songs (sometimes)

### ISSUE THREAD

**Issue by whitetxt** [Tiny-Foxes/superuser-outfox#22]
The game crashed when I attempted to play `Over the "Period"`, before the song was first shown on screen.
This is an issue with the theme, as no other themes have this issue.
The crash seems inconsistent, or very specific, because it worked again when I tried later in the day (without updating the theme).

Crash Log: [ProjectOutfox.Crash.2023-03-12--19.43.49.log](https://github.com/Tiny-Foxes/superuser-outfox/files/10957285/ProjectOutfox.Crash.2023-03-12--19.43.49.log)

**Comment by Sudospective** [comment]
what game mode were you playing when this happened? are you able to provide a copy of the simfile?

**Comment by whitetxt** [comment]
https://zenius-i-vanisher.com/v5.2/viewsimfile.php?simfileid=26671
That is the simfile, I was playing on dance.

**Comment by Sudospective** [comment]
thanks, ill check into this today! what build of outfox are you using?

**Comment by whitetxt** [comment]
The latest version on Steam (0.5 28426bf38a)

**Comment by JoseVarelaP** [comment]
Looking through the crash history, it seems it crashed trying to generate a ScoreDisplay for the player, but the defined PlayMode was out of bounds (7, when there's only 6 of them) so it triggered an assert.

**Comment by Sudospective** [comment]
huh...thats odd, ill definitely check this out, thanks you two!

**Comment by Sudospective** [comment]
new release coming up, should resolve this
