### ISSUE TITLE
Lua errors during difficulty selection

### ISSUE THREAD

**Issue by whitetxt** [Tiny-Foxes/superuser-outfox#23]
Lua errors happen during difficulty selection.
Example:
https://user-images.githubusercontent.com/54776821/227795938-9948e471-8457-473e-926e-68ca33cd0815.mp4
Error:
```
/Appearance/Themes/superuser-outfox-stable/BGAnimations/OFSelectDifficulty overlay.lua:491: unknown(self = (null),nd = (null))
19:16:28	WARNING		Main Thread	Error playing command:...utfox-stable/BGAnimations/OFSelectDifficulty overlay.lua:491: NoteData table entry 1 has an out of range column. (Attempted to use column 7, maximum is 4)
[C]: SetNoteDataFromLua( = (null))
/Appearance/Themes/superuser-outfox-stable/BGAnimations/OFSelectDifficulty overlay.lua:491: unknown(self = (null),nd = (null))
19:16:28	WARNING		Main Thread	Error playing command:...utfox-stable/BGAnimations/OFSelectDifficulty overlay.lua:491: NoteData table entry 1 has an out of range column. (Attempted to use column 7, maximum is 4)
[C]: SetNoteDataFromLua( = (null))
```
Full Log:
[ProjectOutfox-default.ThemeLua.2023-03-26--19.14.59.log](https://github.com/Tiny-Foxes/superuser-outfox/files/11072626/ProjectOutfox-default.ThemeLua.2023-03-26--19.14.59.log)

**Comment by Sudospective** [comment]
ah, yeah, this is an issue with the chart preview. ive been getting this a lot as well and im currently looking into the issue. thanks for the report!

**Comment by Sudospective** [comment]
got this issue fixed in the branch, waiting for a release now (keep in mind this will only be available in alpha v)
