### ISSUE TITLE
Solo chart songs not showing in song select.

### ISSUE THREAD

**Issue by agleaupper** [Tiny-Foxes/superuser-outfox#24]
Songs for which only the Solo score exists are not displayed on the music selection screen.
If there are other charts such as Single or Double, they will be displayed and can select them.

I tried this package.
https://[search.stepmaniaonline.net/pack/id/30](https://search.stepmaniaonline.net/pack/id/30)

(I'm using Deepl translation, so sorry if there are any strange expressions.)

**Comment by Sudospective** [comment]
Which version of the theme are you using, and which version of OutFox?

**Comment by Sudospective** [comment]
Check with the releases over at https://git.sudospective.net/superuser-outfox/~tags and see if those give you any better luck.
If you have Alpha 4, use v1.6.0. If you have Alpha 5, you can try v2.0.0.

**Comment by Sudospective** [comment]
Should be fixed in latest release, if you still have trouble, feel free to open this issue again
