### ISSUE TITLE
Toggle for judgment animations.

### ISSUE THREAD

**Issue by ChocoboGamer** [Tiny-Foxes/superuser-outfox#3]
I believe that a toggle for judgment animations in gameplay would be good for various high-level players who can find the extra on-screen movement distracting.

**Comment by Sudospective** [comment]
What I think will happen for this is I'll end up creating a new option row in ScreenOptionsService called "Superuser Options" that will allow you to customize things like wheel bindings, theme colors, etc.

**Comment by Sudospective** [comment]
Implemented and set to be included in next release. Thanks for the suggestion!
